spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        highlight_sql: true

logging:
  level:
    # sql 바인딩 파라미터 로깅
#    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace