global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:9090' ]
    scrape_interval: 30s

  - job_name: 'spring-boot'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]
    scrape_interval: 30s

  - job_name: 'mysql-exporter'
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'mysql-exporter:9104' ]
    scrape_interval: 30s

  - job_name: redis_exporter
    static_configs:
      - targets: [ 'redis-exporter:9121' ]
    scrape_interval: 30s
